# Railway deployment configuration

apiVersion: 1
services:
  - id: ai-textbook-backend
    buildType: Dockerfile
    dockerfilePath: Dockerfile
    env:
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - port: 8000
        protocol: http
        name: http
        description: FastAPI application port